version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcloud-rest-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "e_commerce_api.wsgi:application"]