# Generated by Django 4.2.11 on 2024-05-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="reset_pasword_expire",
            new_name="reset_password_expire",
        ),
    ]
